# -*- coding: utf-8 -*-
"""Untitled107.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IrjgEAXzbi_nQAPKybqAEd1101_pE4rv
"""

import geopandas as gpd
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from libpysal.weights import Queen, Rook, KNN
from libpysal.weights import lag_spatial
from esda.moran import Moran
from spreg import ML_Lag, ML_Error

import statsmodels.api as sm
from statsmodels.stats.outliers_influence import variance_inflation_factor
from statsmodels.stats.diagnostic import het_breuschpagan
from scipy.stats import shapiro

gdf = gpd.read_file("/content/covid19_eng.gpkg")

print(gdf.shape)
print(gdf.columns)

y_var = "Human_health_and_social_work"

x_vars = [
    "Education",
    "Financial_and_insurance",
    "Information_and_communication",
    "Real_estate"
]

gdf = gdf[[y_var] + x_vars + ["geometry"]].dropna()

fig, ax = plt.subplots(1,1, figsize=(8,6))
gdf.plot(column=y_var, cmap='viridis', legend=True, ax=ax)
plt.title("Peta Human Health and Social Work")
plt.show()

plt.figure(figsize=(10,5))
sns.boxplot(data=gdf[x_vars + [y_var]])
plt.xticks(rotation=45)
plt.title("Boxplot Variabel")
plt.show()

desc_stats = gdf[x_vars + [y_var]].describe().T
desc_stats["variance"] = gdf[x_vars + [y_var]].var()
desc_stats["range"] = desc_stats["max"] - desc_stats["min"]
desc_stats["cv_%"] = (desc_stats["std"] / desc_stats["mean"]) * 100

print(desc_stats.round(3))

import matplotlib.pyplot as plt
import seaborn as sns
import math

# Gabungkan semua variabel
all_vars = [y_var] + x_vars
n = len(all_vars)

# Tentukan jumlah kolom (misal 3)
cols = 3
rows = math.ceil(n / cols)

plt.figure(figsize=(cols*5, rows*4))

for i, var in enumerate(all_vars):
    plt.subplot(rows, cols, i+1)
    sns.histplot(gdf[var], kde=True)
    plt.title(f"Distribusi {var}")
    plt.tight_layout()

plt.show()

import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import math

all_vars = [y_var] + x_vars
n = len(all_vars)

# Ukuran figure besar
fig = plt.figure(figsize=(20, 16))

# =========================================
# 1️⃣ HISTOGRAM (baris 1-2)
# =========================================
cols = 3
rows_hist = math.ceil(n / cols)

for i, var in enumerate(all_vars):
    ax = plt.subplot(4, cols, i+1)
    sns.histplot(gdf[var], kde=True, ax=ax)
    ax.set_title(f"Histogram {var}")

# =========================================
# 2️⃣ BOXPLOT (baris berikutnya)
# =========================================
ax_box = plt.subplot(4, 1, 3)
sns.boxplot(data=gdf[all_vars], ax=ax_box)
ax_box.set_title("Boxplot Semua Variabel")
ax_box.tick_params(axis='x', rotation=45)

# =========================================
# 3️⃣ CORRELATION HEATMAP
# =========================================
ax_corr = plt.subplot(4, 1, 4)
corr = gdf[all_vars].corr()
sns.heatmap(corr, annot=True, cmap="coolwarm", fmt=".2f", ax=ax_corr)
ax_corr.set_title("Correlation Matrix")

plt.tight_layout()
plt.show()

fig, ax = plt.subplots(1,1, figsize=(8,6))
gdf.plot(column=y_var,
         scheme='quantiles',
         k=5,
         cmap='viridis',
         legend=True,
         ax=ax)
plt.title("Peta Quantile - " + y_var)
plt.show()

corr_matrix = gdf[x_vars + [y_var]].corr()

plt.figure(figsize=(8,6))
sns.heatmap(corr_matrix,
            annot=True,
            cmap='coolwarm',
            fmt=".2f")
plt.title("Matriks Korelasi")
plt.show()

X = gdf[x_vars]
X = sm.add_constant(X)
y = gdf[y_var]

ols_model = sm.OLS(y, X).fit()
print(ols_model.summary())

stat, p = shapiro(ols_model.resid)
print("Shapiro p-value:", p)

vif_data = pd.DataFrame()
vif_data["Variable"] = X.columns
vif_data["VIF"] = [variance_inflation_factor(X.values, i)
                   for i in range(X.shape[1])]
print(vif_data)

bp_test = het_breuschpagan(ols_model.resid, X)
print("Breusch-Pagan p-value:", bp_test[1])

w_queen = Queen.from_dataframe(gdf)
w_rook = Rook.from_dataframe(gdf)
w_knn = KNN.from_dataframe(gdf, k=5)

w_queen.transform = 'r'
w_rook.transform = 'r'
w_knn.transform = 'r'

for var in [y_var] + x_vars:
    mi = Moran(gdf[var], w_queen)
    print(f"{var}")
    print("Moran I:", round(mi.I,4))
    print("p-value:", round(mi.p_sim,4))
    print("----------------------")

from esda.moran import Moran

residual = ols_model.resid
mi_resid = Moran(residual, w_queen)

print("Moran I residual:", mi_resid.I)
print("p-value:", mi_resid.p_sim)

y_sp = gdf[y_var].values.reshape(-1,1)
X_sp = gdf[x_vars].values

sar_model = ML_Lag(y_sp, X_sp, w=w_queen,
                   name_y=y_var, name_x=x_vars)

print(sar_model.summary)

sem_model = ML_Error(y_sp, X_sp, w=w_queen,
                     name_y=y_var, name_x=x_vars)

print(sem_model.summary)

weights_dict = {
    "Queen": w_queen,
    "Rook": w_rook,
    "KNN": w_knn
}

for name, w in weights_dict.items():
    model = ML_Error(y_sp, X_sp, w=w)
    print(name, "AIC:", model.aic)

from splot.esda import moran_scatterplot
from esda.moran import Moran

mi = Moran(gdf[y_var], w_queen)

fig, ax = moran_scatterplot(mi)
plt.title("Moran Scatterplot - " + y_var)
plt.show()

best_model = ML_Error(y_sp, X_sp, w=w_queen)

gdf["residual"] = best_model.u

fig, ax = plt.subplots(1,1, figsize=(8,6))
gdf.plot(column="residual", cmap='coolwarm', legend=True, ax=ax)
plt.title("Peta Residual SAR")
plt.show()

print("OLS R2:", round(ols_model.rsquared,4))
print("SAR AIC:", round(sar_model.aic,4))
print("SEM AIC:", round(sem_model.aic,4))

from libpysal.weights import Queen

w_queen = Queen.from_dataframe(gdf)
w_queen.transform = 'r'

from esda.moran import Moran_Local

lisa = Moran_Local(gdf[y_var], w_queen)

# Tambahkan ke dataframe
gdf["local_I"] = lisa.Is
gdf["p_sim"] = lisa.p_sim
gdf["quadrant"] = lisa.q

print(gdf.columns)

gdf["cluster"] = "Not significant"

gdf.loc[(gdf["quadrant"]==1) & (gdf["p_sim"]<0.05), "cluster"] = "High-High"
gdf.loc[(gdf["quadrant"]==2) & (gdf["p_sim"]<0.05), "cluster"] = "Low-High"
gdf.loc[(gdf["quadrant"]==3) & (gdf["p_sim"]<0.05), "cluster"] = "Low-Low"
gdf.loc[(gdf["quadrant"]==4) & (gdf["p_sim"]<0.05), "cluster"] = "High-Low"

fig, ax = plt.subplots(1,1, figsize=(8,6))
gdf.plot(column="cluster",
         categorical=True,
         legend=True,
         ax=ax)
plt.title("Peta LISA Cluster - " + y_var)
plt.show()

